name: Checks
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches-ignore:
      - 'nobuild**'
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  UnitTests:
    name: 'Tests and Builds'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - name: Install
        run: |
          bun install --frozen-lockfile
      - name: Build Succeeds
        run: |
          bun run build
      - name: Format Check
        run: |
          bun run lint
